/*
Milestone #3

Group 11

Gordon Tan 147206221
Sasawat Yimleang 114036221
Meet Chetanbhai Sakariya

Date:08/13/2023
*/


CREATE TABLE customers (
    custID NUMBER(8) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    firstName VARCHAR(20) DEFAULT NULL,
    lastName VARCHAR(30) DEFAULT NULL,
    phoneNumber NUMBER(10) DEFAULT NULL,
    email VARCHAR(50) DEFAULT NULL,
    address VARCHAR(50) DEFAULT NULL
    );
     
CREATE TABLE employees
(
empID NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
firstName VARCHAR(20) NOT NULL,
lastName VARCHAR(30) NOT NULL,
userName VARCHAR(30) NOT NULL,
password VARCHAR(20) NOT NULL,
sin NUMBER(9) NOT NULL,
dob DATE NOT NULL,
email VARCHAR(50) NOT NULL,
phoneNumber NUMBER(10) NOT NULL
);

CREATE TABLE orders(
orderID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
custID NUMBER(8) NOT NULL,
empID NUMBER(4) NOT NULL,
status VARCHAR(10) NOT NULL,
dateOfPurchase DATE NOT NULL,
dateShipped DATE DEFAULT NULL,
transactionType VARCHAR(10) NOT NULL,
CONSTRAINT customers_orders_FK FOREIGN KEY(custID)
REFERENCES customers(custID),
CONSTRAINT employees_orders_FK FOREIGN KEY(empID)
REFERENCES employees(empID)
);

CREATE TABLE publishers
(
publisherID NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
companyName VARCHAR(30) NOT NULL,
country CHAR(3) NOT NULL,
contactEmail VARCHAR(50) NOT NULL
);

CREATE TABLE platforms
(
platformID NUMBER(4)GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
platformName VARCHAR(30) NOT NULL
);

CREATE TABLE videogames
(gameID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
productName VARCHAR(30) NOT NULL,
genre VARCHAR(10) NOT NULL,
sellingPrice NUMBER(10,2) NOT NULL,
ageRating CHAR(1) NOT NULL,
stockQuantity INT DEFAULT NULL,
supplierCost NUMBER(10,2) NOT NULL,
publisherID NUMBER(5) NOT NULL,
releaseDate DATE NOT NULL,
platformID NUMBER(4) NOT NULL,
CONSTRAINT publishers_videogames_FK FOREIGN KEY (publisherID)
REFERENCES publishers(publisherID),
CONSTRAINT platforms_videogames_FK FOREIGN KEY(platformID)
REFERENCES platforms(platformID)
);

CREATE TABLE supply_orders
(supplyOrderID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
empID NUMBER(4) NOT NULL,
status VARCHAR(10) NOT NULL,
dateOfPurchase DATE NOT NULL,
storeAddress VARCHAR(50) NOT NULL,
paidPrice NUMBER(10,2) NOT NULL,
dateShipped DATE DEFAULT NULL,
CONSTRAINT employees_supply_orders_FK FOREIGN KEY(empID)
REFERENCES employees(empID)
);

CREATE TABLE order_videogames
(
orderID INT ,
gameID INT,
status VARCHAR(10) NOT NULL,
paidPrice NUMBER(10,2) NOT NULL,
quantity INT NOT NULL,
CONSTRAINT order_videogames_PK PRIMARY KEY (orderID, gameID),
CONSTRAINT orders_order_videogames_FK FOREIGN KEY(orderID)
REFERENCES orders(orderID),
CONSTRAINT videogames_order_videogames_FK FOREIGN KEY(gameID)
REFERENCES videogames(gameID)
);

CREATE TABLE supply_order_videogames
(
supplyOrderID INT,
gameID INT,
status VARCHAR(10) NOT NULL,
paidPrice NUMBER(10,2) NOT NULL,
quantity INT NOT NULL,
CONSTRAINT so_videogames_PK PRIMARY KEY (supplyOrderID, gameID),
CONSTRAINT sorders_sovideogames_FK FOREIGN KEY(supplyOrderID)
REFERENCES supply_orders(supplyOrderID),
CONSTRAINT videogames_sovideogames_FK FOREIGN KEY(gameID)
REFERENCES videoGames(gameID)
);

    
INSERT INTO customers VALUES (111, 'Janet', 'Dorshe',9051732221,'something@mail.com', '725 Pie St. Markham ON');
INSERT INTO customers VALUES (112, NULL, NULL,NULL,NULL, NULL);
INSERT INTO customers VALUES (113, 'Alice', 'Wingding',9051232121,'grass@mail.com', '700 Normal St. Aurora ON');
INSERT INTO customers VALUES (114, 'Chad', 'Boswick',NULL,NULL, NULL);
INSERT INTO customers VALUES (115, NULL,NULL,NULL,NULL,NULL);
INSERT INTO customers VALUES ( 116, 'Jack', 'Smith',NULL,'chipper@mail.com', '711 Ronald Dr. Markham ON');
INSERT INTO customers  VALUES (117, 'Dan', 'Goodman',9051132111,NULL, '712 Front St. Markham ON');
INSERT INTO customers  VALUES (118, 'Saul', 'Goodman',9051002221,'lawyer@mail.com', '500 Zombie St. Markham ON');
INSERT INTO customers VALUES (119, 'Walter', 'White',9051113333,'breaking@mail.com', '625 Poncho Dr. Aurora ON');
INSERT INTO customers  VALUES (120, 'Jessie', 'Pinkman',2891732221,'bad@mailer.com', '125 Arizona St. Waterloo ON');
INSERT INTO customers  VALUES (121, 'Francis', 'Bob',2891112221,'bobby@mail.com', '111 Lizard Dr. Markham ON');
INSERT INTO customers  VALUES (122, NULL, NULL,NULL,NULL, NULL);
INSERT INTO customers  VALUES (123, 'Smith', 'Jack',NULL,NULL, NULL);
INSERT INTO customers  VALUES (124, NULL, NULL,NULL,NULL, NULL);
INSERT INTO customers VALUES (125, 'Jack', 'Nicholson',NULL,'theShining@mail.com', '625 Hell Dr. Bradford ON');
INSERT INTO customers  VALUES (126, 'Leon', 'Dennis',NULL,'meth@mail.com', '111 Stone Dr. London ON');
INSERT INTO customers  VALUES (127, 'Sally', 'Feldstein',9051231234,NULL, '121 Baldwin St. Waterloo ON');
INSERT INTO customers  VALUES (128, NULL, NULL,NULL,NULL, NULL);
INSERT INTO customers  VALUES (129, 'Nacho', 'Varga',2892002221,'drugs@gmail.com', '111 Hazard St. Barrie ON');
INSERT INTO customers  VALUES (130, 'Robin', 'Hood',2891002220,'poor@yahoo.com', '111 Steal Dr. Bradford ON');

INSERT INTO employees VALUES (111, 'Bob', 'Dole','bobDole2','password', '123456789', to_date('1960-08-11', 'YYYY-MM-DD'), 'BobDole@company.ca', 2491111234);
INSERT INTO employees VALUES (112, 'Jessie', 'Jacksan','JessieJ','password1', '123456780', TO_DATE('1950-06-12', 'YYYY-MM-DD'), 'JessieJacksan@company.ca',2491091234);
INSERT INTO employees VALUES (113, 'Donkey', 'Kong','DK','passwordD', '223456780', TO_DATE('1970-06-12', 'YYYY-MM-DD'), 'DK@company.ca',2491011234);
INSERT INTO employees VALUES (114, 'Martin', 'Luther','MartinLuth','passwordL', '323456780', TO_DATE('1952-02-12', 'YYYY-MM-DD'), 'ML@company.ca',2498011234);
INSERT INTO employees VALUES (115, 'John', 'Kennedy','JKrocks','passwordK', '423456780', TO_DATE('1954-01-12', 'YYYY-MM-DD'), 'JK@company.ca',2499011234);
INSERT INTO employees VALUES (116, 'Harley', 'Quinn','Harley_Q','passwordQ', '523456780', TO_DATE('1953-01-12', 'YYYY-MM-DD'), 'HQ2@company.ca',2494441234);
INSERT INTO employees VALUES (117, 'Super', 'Man','TheSuperMan','pasordS', '623456780', TO_DATE('1941-01-12', 'YYYY-MM-DD'), 'superman@company.ca',2495551234);
INSERT INTO employees VALUES (118, 'Homer', 'Simpson','DrunkHomer','drunkPass', '723456780', TO_DATE('1961-02-24', 'YYYY-MM-DD'), 'homersimpson@company.ca',2496661234);
INSERT INTO employees VALUES (119, 'Marge', 'Simpson','Marge_si','passSimp', '823456780', TO_DATE('1980-02-24', 'YYYY-MM-DD'), 'margesimpson@company.ca',2497771234);
INSERT INTO employees VALUES (120, 'Sideshow', 'Bob','SideshowMan','passman', '933456780', TO_DATE('1981-03-21', 'YYYY-MM-DD'), 'sideshowB@company.ca',2498881234);
INSERT INTO employees VALUES (121, 'Krusty', 'Klown','KrustyUser','passK', '900016780', TO_DATE('1970-01-21', 'YYYY-MM-DD'), 'krustyklown@company.ca',2499991234);
INSERT INTO employees VALUES (122, 'Spongebob', 'Squarepants','spongeDudeUser','passsponge', '911116780', TO_DATE('1969-04-21', 'YYYY-MM-DD'), 'spongebob@company.ca',2490111234);
INSERT INTO employees VALUES (123, 'Squidward', 'Tentacles','grumpySquid','squidPassword', '911122222', TO_DATE('1966-04-21', 'YYYY-MM-DD'), 'SquidWard@company.ca',2490121234);
INSERT INTO employees VALUES (124, 'Patrick', 'Star','funPatrick_star','starPPassword', '911111111', TO_DATE('1965-11-21', 'YYYY-MM-DD'), 'starPatrick@company.ca',2490131234);
INSERT INTO employees VALUES (125, 'Komeji', 'Son','PoliteKomeji','KomePassword', '922222222', TO_DATE('1955-10-21', 'YYYY-MM-DD'), 'KomejiSan@company.ca',2490141234);
INSERT INTO employees VALUES (126, 'Dwayne', 'Johnson','TheDwayneRock','dddePasswordR', '212222221', TO_DATE('1995-09-21', 'YYYY-MM-DD'), 'DwayneJohnson@company.ca',2490151234);
INSERT INTO employees VALUES (127, 'Miharu', 'Desu','DesuM','dddePaMMM', '333333331', TO_DATE('1986-07-11', 'YYYY-MM-DD'), 'MiharuDesuxX@company.ca',2490161234);
INSERT INTO employees VALUES (128, 'Larry', 'Lobster','Larry_BuffUser','somethingPassword2', '333333335', TO_DATE('1977-02-20', 'YYYY-MM-DD'), 'LarryLobster@company.ca',2490171234);
INSERT INTO employees VALUES (129, 'Joe', 'Biding','Biding_Joe1','thisisPaword2', '444444444', TO_DATE('1971-01-05', 'YYYY-MM-DD'), 'JoeBiding@company.ca',2490181234);
INSERT INTO employees VALUES (130, 'Sanders', 'Sandy','SandySand','isSawSrd2', '555555555', TO_DATE('1950-09-12', 'YYYY-MM-DD'), 'SandersSandy0@company.ca',2490191234);

INSERT INTO orders VALUES (1001,111,111,'Processing' ,TO_DATE('2023-10-21', 'YYYY-MM-DD'),NULL, 'debit');
INSERT INTO orders VALUES (1002,112,112,'Delivered' ,TO_DATE('2021-10-21', 'YYYY-MM-DD'), TO_DATE('2021-10-21', 'YYYY-MM-DD'), 'cash');
INSERT INTO orders VALUES (1003,113,113,'Pending' ,TO_DATE('2023-03-21', 'YYYY-MM-DD'),NULL, 'debit');
INSERT INTO orders VALUES (1004,114,114,'Delivered' ,TO_DATE('2023-01-21', 'YYYY-MM-DD'),TO_DATE('2023-01-21', 'YYYY-MM-DD'), 'credit');
INSERT INTO orders VALUES (1005,115,115,'Delivered' ,TO_DATE('2019-01-21', 'YYYY-MM-DD'),TO_DATE('2019-01-21', 'YYYY-MM-DD'), 'cash');
INSERT INTO orders VALUES (1006,116,116,'Cancelled', TO_DATE('2016-01-21', 'YYYY-MM-DD'),NULL, 'debit');
INSERT INTO orders VALUES (1007,117,117,'Cancelled', TO_DATE('2015-01-21', 'YYYY-MM-DD'),NULL, 'credit');
INSERT INTO orders VALUES (1008,118,118,'Processing', TO_DATE('2023-05-17', 'YYYY-MM-DD'),NULL, 'credit');
INSERT INTO orders VALUES (1009,119,119,'Delivered', TO_DATE('2023-05-17', 'YYYY-MM-DD'),TO_DATE('2023-06-17', 'YYYY-MM-DD'), 'debit');
INSERT INTO orders VALUES (1010,120,120,'Delivered', TO_DATE('2023-06-10', 'YYYY-MM-DD'),TO_DATE('2023-06-22', 'YYYY-MM-DD'), 'credit');
INSERT INTO orders VALUES (1011,121,121,'Refund', TO_DATE('2023-07-10', 'YYYY-MM-DD'),TO_DATE('2023-07-22', 'YYYY-MM-DD'), 'credit');
INSERT INTO orders VALUES (1012,122,122,'Refund', TO_DATE('2023-07-12', 'YYYY-MM-DD'),TO_DATE('2023-07-12', 'YYYY-MM-DD'), 'cash');
INSERT INTO orders VALUES (1013,123,123,'Delivered', TO_DATE('2023-07-13', 'YYYY-MM-DD'),TO_DATE('2023-07-13', 'YYYY-MM-DD'), 'credit');
INSERT INTO orders VALUES (1014,124,124,'Refund', TO_DATE('2023-05-10', 'YYYY-MM-DD'),TO_DATE('2023-05-10', 'YYYY-MM-DD'), 'cash');
INSERT INTO orders VALUES (1015,125,125,'Processing', TO_DATE('2023-04-13', 'YYYY-MM-DD'),NULL, 'credit');
INSERT INTO orders VALUES (1016,126,126,'Processing', TO_DATE('2023-06-25', 'YYYY-MM-DD'),NULL, 'credit');
INSERT INTO orders VALUES (1017,127,127,'Delivered', TO_DATE('2023-03-25', 'YYYY-MM-DD'),TO_DATE('2023-04-21', 'YYYY-MM-DD'), 'credit');
INSERT INTO orders VALUES (1018,128,128,'Delivered', TO_DATE('2023-03-25', 'YYYY-MM-DD'),TO_DATE('2023-03-25', 'YYYY-MM-DD'), 'cash');
INSERT INTO orders VALUES (1019,129,129,'Processing', TO_DATE('2023-01-19', 'YYYY-MM-DD'),NULL, 'credit');
INSERT INTO orders VALUES (1020,130,130,'Cancelled', TO_DATE('2023-03-19', 'YYYY-MM-DD'),NULL, 'debit');

INSERT INTO publishers VALUES (101,'Ubisoft','CAN','Ubisoft@mail.com'); /*224 Wallace Ave #200, Toronto, ON*/
INSERT INTO publishers VALUES (102,'Nintendo','JPN','Nintendo@mail.com'); /*1 Hokotate-cho, Kamitoba, Minami-ku, Kyoto, Japan*/
INSERT INTO publishers VALUES (103,'id Software','USA','idSoftware@mail.com'); /*1500 N Greenville Ave, Richardson, TX*/
INSERT INTO publishers VALUES (104,'BioWare','CAN','BioWare@mail.com'); /*101 St NW #1800, Edmonton, AB*/
INSERT INTO publishers VALUES (105,'Naughty Dog','USA','NaughtyDog@mail.com'); /*2425 Olympic Blvd Ste 3000W, Santa Monica, CA*/
INSERT INTO publishers VALUES (106,'Square Enix','JPN','SquareEnix@mail.com'); /*6-27-30 Shinjuku, Shinjuku-ku, Tokyo, Japan*/
INSERT INTO publishers VALUES (107,'Activision Blizzard','USA','ActivisionBlizzard@mail.com'); /*2701 Olympic Blvd Bldg B, Santa Monica, CA*/
INSERT INTO publishers VALUES (108,'Epic Games','USA','EpicGames@mail.com'); /*620 Crossroads Blvd, Cary, NC*/
INSERT INTO publishers VALUES (109,'Electronic Arts','USA','EAGames@mail.com'); /*209 Redwood Shores Parkway, Redwood City, CA*/
INSERT INTO publishers VALUES (110,'Rockstar Games','USA','RockstarGames@mail.com'); /*110 W 44th St, New York City, NY*/
INSERT INTO publishers VALUES (111,'Bethesda Softworks','USA','Bethesda@mail.com'); /*1370 Piccard Dr # 120, Rockville, MD*/
INSERT INTO publishers VALUES (112,'Insomniac Games','USA','InsomniacGames@mail.com'); /*2255 N Ontario St, Burbank, CA*/
INSERT INTO publishers VALUES (113,'Bungie','USA','Bungie@mail.com'); /*550 106th NE, Suite #207 Bellevue, WA*/
INSERT INTO publishers VALUES (114,'FromSoftware','JPN','FromSoftware@mail.com'); /*2-26-2 Shibuya-ku, Sasaduka, Tokyo, 151-0073, Japan*/
INSERT INTO publishers VALUES (115,'Capcom','JPN','Capcom@mail.com'); /*2-2-14, Awaji-cho, Chuo-ku, Osaka*/
INSERT INTO publishers VALUES (116,'Obsidian Entertainment','USA','ObsidianEntertainment@mail.com'); /*100 Spectrum Center Dr Ste 200, Irvine, CA*/
INSERT INTO publishers VALUES (117,'Bandai Namco','JPN','BandaiNamco@mail.com'); /*2-37-25, Eitai, Koto-ku, Tokyo 135-0034, Japan*/
INSERT INTO publishers VALUES (118,'Atlus','JPN','Atlus@mail.com'); /*1-1-1 Nishishinagawa, Shinagawa-ku � Tokyo, Japan*/
INSERT INTO publishers VALUES (119,'Konami','JPN','konami@mail.com'); /*1-11-1, Ginza, Chuo-ku, Tokyo, Japan*/
INSERT INTO publishers VALUES (120,'Arc System Works','JPN','ArcSystemWorks@mail.com'); /*2-3-9, Shinyokohama, Kohokuku,Yokohama,Kanagawa, Japan*/

INSERT INTO platforms VALUES (101, 'PlayStation4');
INSERT INTO platforms VALUES (102, 'PlayStation5');
INSERT INTO platforms VALUES (103, 'Xbox One');
INSERT INTO platforms VALUES (104, 'Xbox 360');
INSERT INTO platforms VALUES (105, 'Nintendo Wii');
INSERT INTO platforms VALUES (106, 'Nintendo Switch');

INSERT INTO videogames VALUES (100001, 'Watch Dogs', 'Action', 19.99, 'E', 5, 16.50, 101, TO_DATE('2017-05-26', 'YYYY-MM-DD'), 101 );
INSERT INTO videogames VALUES (100002, 'MASS EFFECT:ANDROMEDA', 'RPG', 39.99, 'E', 8, 30.25, 104, TO_DATE('2017-03-21', 'YYYY-MM-DD'), 101 );
INSERT INTO videogames VALUES (100003, 'Spider-Man', 'RPG', 49.99, 'T', 10, 39.50, 112, TO_DATE('2019-08-28', 'YYYY-MM-DD'), 101 );
INSERT INTO videogames VALUES (100004, 'The Last of Us Part I', 'Action', 89.99, 'E', 6, 62.50, 105, TO_DATE('2022-09-02', 'YYYY-MM-DD'), 102 );
INSERT INTO videogames VALUES (100005, 'Final Fantasy XVI', 'Action', 93.49, 'M', 20, 80.25, 106, TO_DATE('2023-06-22', 'YYYY-MM-DD'), 102 );
INSERT INTO videogames VALUES (100006, 'Sekiro: Shadows Die Twice', 'Action', 79.99, 'M', 15, 62.00, 114, TO_DATE('2019-03-22', 'YYYY-MM-DD'), 102 );
INSERT INTO videogames VALUES (100007, 'Call of Duty: Vanguard', 'FPS', 89.99, 'M', 4, 70.00, 107, TO_DATE('2021-05-11', 'YYYY-MM-DD'), 102 );
INSERT INTO videogames VALUES (100008, 'DNF Duel', 'Fighting', 64.99, 'T', 5, 48.25, 120, TO_DATE('2022-06-28', 'YYYY-MM-DD'), 102 );
INSERT INTO videogames VALUES (100009, 'Gears 5', 'Action', 49.99, 'M', 2, 39.50, 108, TO_DATE('2017-07-21', 'YYYY-MM-DD'), 104 );
INSERT INTO videogames VALUES (100010, 'The Elder Scrolls V', 'RPG', 49.99, 'M', 10, 35.50, 111, TO_DATE('2021-11-11', 'YYYY-MM-DD'), 104 );
INSERT INTO videogames VALUES (100011, 'Little Nightmares II', 'Puzzle', 29.99, 'T', 4, 21.00, 117, TO_DATE('2021-11-02', 'YYYY-MM-DD'), 104 );
INSERT INTO videogames VALUES (100012, 'METAL GEAR SURVIVE', 'Survival', 29.99, 'M', 6, 22.50, 119, TO_DATE('2018-02-19', 'YYYY-MM-DD'), 104 );
INSERT INTO videogames VALUES (100013, 'Halo 3', 'FPS', 9.99, 'T', 1, 5.25, 113, TO_DATE('2007-11-26', 'YYYY-MM-DD'), 104 );
INSERT INTO videogames VALUES (100014, 'Fallout: New Vegas', 'Action', 9.99, 'T', 3, 6.75, 116, TO_DATE('2010-10-19', 'YYYY-MM-DD'), 104 );
INSERT INTO videogames VALUES (100015, 'Grand Theft Auto V', 'RPG', 29.99, 'M', 5, 21.50, 110, TO_DATE('2017-12-18', 'YYYY-MM-DD'), 105 );
INSERT INTO videogames VALUES (100016, 'Left 4 Dead 2', 'FPS', 45.45, 'M', 2, 26.75, 109, TO_DATE('2009-11-16', 'YYYY-MM-DD'), 105 );
INSERT INTO videogames VALUES (100017, 'Wii Sports', 'RPG', 149.99, 'T', 5, 95.00, 102, TO_DATE('2009-06-24', 'YYYY-MM-DD'), 105 );
INSERT INTO videogames VALUES (100018, 'Mario Kart Wii', 'Family', 96.99, 'T', 5, 80.00, 102, TO_DATE('2008-04-10', 'YYYY-MM-DD'), 105 );
INSERT INTO videogames VALUES (100019, 'Resident Evil 4', 'RPG', 91.99, 'M', 4, 82.00, 115, TO_DATE('2009-07-13', 'YYYY-MM-DD'), 105 );
INSERT INTO videogames VALUES (100020, 'Bayonetta 3', 'Action', 59.99, 'M', 8, 45.00, 102, TO_DATE('2022-10-28', 'YYYY-MM-DD'), 106 );
INSERT INTO videogames VALUES (100021, 'DOOM Eternal', 'FPS', 9.99, 'M', 5, 7.50, 103, TO_DATE('2017-11-10', 'YYYY-MM-DD'), 106 );
INSERT INTO videogames VALUES (100022, 'Persona 5 Strikers', 'Action', 59.99, 'M', 8, 41.50, 118, TO_DATE('2021-02-22', 'YYYY-MM-DD'), 106 );

INSERT INTO order_videogames VALUES (1001, 100010, 'Processing', 99.98, 2);
INSERT INTO order_videogames VALUES (1001, 100015, 'Processing', 29.99, 1);
INSERT INTO order_videogames VALUES (1002, 100001, 'Delivered', 19.99, 1);
INSERT INTO order_videogames VALUES (1003, 100003, 'Pending', 49.99, 1);
INSERT INTO order_videogames VALUES (1004, 100013, 'Delivered', 29.97, 3);
INSERT INTO order_videogames VALUES (1005, 100002, 'Delivered', 39.99, 1);
INSERT INTO order_videogames VALUES (1005, 100004, 'Delivered', 89.99, 1);
INSERT INTO order_videogames VALUES (1006, 100014, 'Cancelled', 9.99, 1);
INSERT INTO order_videogames VALUES (1007, 100021, 'Cancelled', 9.99, 1);
INSERT INTO order_videogames VALUES (1008, 100005, 'Processing', 93.49, 1);
INSERT INTO order_videogames VALUES (1008, 100006, 'Processing', 79.99, 1);
INSERT INTO order_videogames VALUES (1009, 100019, 'Delivered', 91.99, 1);
INSERT INTO order_videogames VALUES (1010, 100008, 'Delivered', 194.97, 3);
INSERT INTO order_videogames VALUES (1011, 100020, 'Refund', 59.99, 1);
INSERT INTO order_videogames VALUES (1012, 100003, 'Refund', 99.98, 2);
INSERT INTO order_videogames VALUES (1013, 100004, 'Delivered', 89.99, 1);
INSERT INTO order_videogames VALUES (1013, 100007, 'Delivered', 89.99, 1);
INSERT INTO order_videogames VALUES (1014, 100018, 'Refund', 387.96, 4);
INSERT INTO order_videogames VALUES (1015, 100012, 'Processing', 29.99, 1);
INSERT INTO order_videogames VALUES (1015, 100014, 'Processing', 9.99, 1);
INSERT INTO order_videogames VALUES (1015, 100016, 'Processing', 45.45, 1);
INSERT INTO order_videogames VALUES (1016, 100017, 'Processing', 599.96, 4);
INSERT INTO order_videogames VALUES (1017, 100022, 'Delivered', 59.99, 1);
INSERT INTO order_videogames VALUES (1018, 100019, 'Delivered', 91.99, 1);
INSERT INTO order_videogames VALUES (1019, 100009, 'Processing', 49.99, 1);
INSERT INTO order_videogames VALUES (1019, 100011, 'Processing', 29.99, 1);
INSERT INTO order_videogames VALUES (1020, 100017, 'Cancelled', 299.98, 2);


INSERT INTO supply_orders VALUES (110001, 113, 'Cancelled', TO_DATE('2023-04-01', 'YYYY-MM-DD'), '224 Wallace Ave #200, Toronto, ON', 82.50, NULL);
INSERT INTO supply_orders VALUES (110002, 113, 'Completed', TO_DATE('2023-04-03', 'YYYY-MM-DD'), '1500 N Greenville Ave, Richardson, TX', 151.25, TO_DATE('2023-04-16', 'YYYY-MM-DD'));
INSERT INTO supply_orders VALUES (110003, 115, 'Completed', TO_DATE('2023-04-06', 'YYYY-MM-DD'), '2425 Olympic Blvd Ste 3000W, Santa Monica, CA', 700.00, TO_DATE('2023-04-12', 'YYYY-MM-DD'));
INSERT INTO supply_orders VALUES (110004, 115, 'Cancelled', TO_DATE('2023-04-18', 'YYYY-MM-DD'), '2701 Olympic Blvd Bldg B, Santa Monica, CA', 250.00, NULL);
INSERT INTO supply_orders VALUES (110005, 115, 'Cancelled', TO_DATE('2023-04-22', 'YYYY-MM-DD'), '209 Redwood Shores Parkway, Redwood City, CA', 241.25, NULL);
INSERT INTO supply_orders VALUES (110006, 116, 'Completed', TO_DATE('2023-04-29', 'YYYY-MM-DD'), '1370 Piccard Dr # 120, Rockville, MDn', 225.00, TO_DATE('2023-05-06', 'YYYY-MM-DD'));
INSERT INTO supply_orders VALUES (110007, 116, 'Completed', TO_DATE('2023-05-01', 'YYYY-MM-DD'), '550 106th NE, Suite #207 Bellevue, WA', 210.00, TO_DATE('2023-05-11', 'YYYY-MM-DD'));
INSERT INTO supply_orders VALUES (110008, 112, 'Cancelled', TO_DATE('2023-05-05', 'YYYY-MM-DD'), '2-14, Awaji-cho, Chuo-ku, Osaka', 250.00, NULL);
INSERT INTO supply_orders VALUES (110009, 117, 'Completed', TO_DATE('2023-05-11', 'YYYY-MM-DD'), '100 Spectrum Center Dr Ste 200, Irvine, CA', 250.00, TO_DATE('2023-05-20', 'YYYY-MM-DD'));
INSERT INTO supply_orders VALUES (110010, 121, 'Completed', TO_DATE('2023-05-19', 'YYYY-MM-DD'), '1-1 Nishishinagawa, Shinagawa-ku,  Tokyo, Japan', 107.5, TO_DATE('2023-05-25', 'YYYY-MM-DD'));
INSERT INTO supply_orders VALUES (110011, 121, 'Completed', TO_DATE('2023-05-25', 'YYYY-MM-DD'), '3-9, Shinyokohama,Yokohama,Kanagawa, Japan', 112.5, TO_DATE('2023-06-01', 'YYYY-MM-DD'));
INSERT INTO supply_orders VALUES (110012, 121, 'Cancelled', TO_DATE('2023-06-02', 'YYYY-MM-DD'), '1 Hokotate-cho, Minami-ku, Kyoto, Japan', 802.50, NULL);
INSERT INTO supply_orders VALUES (110013, 121, 'Completed', TO_DATE('2023-06-11', 'YYYY-MM-DD'), '101 St NW #1800, Edmonton, AB', 802.50, TO_DATE('2023-06-16', 'YYYY-MM-DD'));
INSERT INTO supply_orders VALUES (110014, 121, 'Completed', TO_DATE('2023-06-15', 'YYYY-MM-DD'), '27-30 Shinjuku, Tokyo, Japan', 435.00, TO_DATE('2023-06-24', 'YYYY-MM-DD'));
INSERT INTO supply_orders VALUES (110015, 121, 'Completed', TO_DATE('2023-06-21', 'YYYY-MM-DD'), '620 Crossroads Blvd, Cary, NC', 475.00, TO_DATE('2023-06-29', 'YYYY-MM-DD'));
INSERT INTO supply_orders VALUES (110016, 121, 'Shipped', TO_DATE('2023-06-27', 'YYYY-MM-DD'), '110 W 44th St, New York City, NY', 961.25, TO_DATE('2023-07-21', 'YYYY-MM-DD'));
INSERT INTO supply_orders VALUES (110017, 121, 'Processing', TO_DATE('2023-07-04', 'YYYY-MM-DD'), '2255 N Ontario St, Burbank, CA', 105.00, NULL);
INSERT INTO supply_orders VALUES (110018, 121, 'Processing', TO_DATE('2023-07-14', 'YYYY-MM-DD'), '26-2 Shibuya-ku, Tokyo, 151-0073, Japan', 267.50, NULL);
INSERT INTO supply_orders VALUES (110019, 121, 'Delayed', TO_DATE('2023-07-24', 'YYYY-MM-DD'), '100 Spectrum Center Dr Ste 200, Irvine, CA', 248.00, TO_DATE('2023-07-31', 'YYYY-MM-DD'));
INSERT INTO supply_orders VALUES (110020, 121, 'Pending', TO_DATE('2023-07-31', 'YYYY-MM-DD'), '3-9, Shinyokohama,Yokohama,Kanagawa, Japan', 165.00, NULL);

INSERT INTO supply_order_videogames VALUES (110001, 100001, 'Cancelled', 82.50, 5);
INSERT INTO supply_order_videogames VALUES (110002, 100002, 'Completed', 151.25, 5);
INSERT INTO supply_order_videogames VALUES (110003, 100007, 'Completed', 700.00, 5);
INSERT INTO supply_order_videogames VALUES (110004, 100020, 'Cancelled', 250.00, 5);
INSERT INTO supply_order_videogames VALUES (110005, 100008, 'Cancelled', 241.25, 5);
INSERT INTO supply_order_videogames VALUES (110006, 100012, 'Completed', 225.00, 5);
INSERT INTO supply_order_videogames VALUES (110007, 100011, 'Completed', 210.00, 10);
INSERT INTO supply_order_videogames VALUES (110008, 100004, 'Cancelled', 250.00, 4);
INSERT INTO supply_order_videogames VALUES (110009, 100004, 'Completed', 250.00, 4);
INSERT INTO supply_order_videogames VALUES (110010, 100015, 'Completed', 107.5, 5);
INSERT INTO supply_order_videogames VALUES (110011, 100012, 'Completed', 112.5, 5);
INSERT INTO supply_order_videogames VALUES (110012, 100005, 'Cancelled', 802.50, 10);
INSERT INTO supply_order_videogames VALUES (110013, 100005, 'Completed', 802.50, 10);
INSERT INTO supply_order_videogames VALUES (110014, 100020, 'Completed', 360.00, 8);
INSERT INTO supply_order_videogames VALUES (110014, 100021, 'Completed', 75.00, 8);
INSERT INTO supply_order_videogames VALUES (110015, 100017, 'Completed', 475.00, 5);
INSERT INTO supply_order_videogames VALUES (110016, 100005, 'Shipped', 401.25, 5);
INSERT INTO supply_order_videogames VALUES (110016, 100007, 'Completed', 560.00, 4);
INSERT INTO supply_order_videogames VALUES (110017, 100013, 'Processing', 105.00, 20);
INSERT INTO supply_order_videogames VALUES (110018, 100016, 'Processing', 267.50, 10);
INSERT INTO supply_order_videogames VALUES (110019, 100006, 'Delayed', 248.00, 4);
INSERT INTO supply_order_videogames VALUES (110020, 100001, 'Pending', 165.00, 10);


CREATE VIEW VW_GameQuantityInStock AS
SELECT productName,stockQuantity,platformName
FROM videogames INNER JOIN platforms ON videogames.platformID = platforms.platformID
WHERE stockQuantity IS NOT NULL
ORDER BY stockQuantity;
/* This gets the stock quantities of the items in the store along with the associated console. 
It's all sorted by the lowest first then highest in the list. 
This is useful for the business as by seeing from this report what the lowest stocked items are. 
They can plan accordingly ahead of time for supply orders in terms of what's urgently needed at this point in time
before they run out of it and make estimations. */


CREATE VIEW VW_EmployeeContactList AS
SELECT firstName || ' ' || lastName AS employeeName, email, phoneNumber
FROM employees 
ORDER BY employeeName;
/*This grabs the first and last name from the employees table to concatenate them together
in one field for their full name into a list that's in alphabetical order with their contact info. 
This helps the business keep a head count of how many employees they have hired. It can also 
be useful as a reference list for anyone to really learn all the names of employees of the company. 
Having their contact info in there with email and phone number can help anyone commmunicate and contact them 
if neccessary.*/

CREATE VIEW VW_CustomerOrdersProcessing AS
SELECT orders.orderID, firstName || ' ' || lastName AS customerName, TO_CHAR(dateOfPurchase, 'mm/dd/yyyy') AS purchaseDate, 
TO_CHAR(dateShipped, 'mm/dd/yyyy') AS shipDate, productName, dateShipped - dateOfPurchase AS processingDays
FROM customers INNER JOIN orders ON customers.custID = orders.custID INNER JOIN order_videogames ON orders.orderID = order_videogames.orderID 
INNER JOIN videogames ON videogames.gameID = order_videogames.gameID  
WHERE (orders.status = 'Delivered' OR orders.status = 'Refund') AND (transactionType!='cash' AND (dateShipped - dateOfPurchase)!=0)
ORDER BY processingDays;
/*This takes the orders that have shipped from the orders list and calculates in 
days how long each one took for order processing showing the product names and customer names. It sorts 
it from lowest number of days to highest. By doing this it gives valuable information 
to the company in terms of how efficient the order process is for them. It can help identify areas 
of issue and any long hold ups. As it's very important as well to inform customers how long their 
delivery may take on average for maximum customer satisfication.*/


CREATE VIEW VW_SupplyOrdersProcessing AS
SELECT supply_orders.supplyOrderID, companyName, TO_CHAR(dateOfPurchase, 'mm/dd/yyyy') AS purchaseDate, 
TO_CHAR(dateShipped, 'mm/dd/yyyy') AS shipDate, productName, dateShipped - dateOfPurchase AS processingDays
FROM publishers INNER JOIN videogames ON publishers.publisherID = videogames.publisherID
INNER JOIN supply_order_videogames ON videogames.gameID = supply_order_videogames.gameID
INNER JOIN supply_orders ON supply_orders.supplyOrderID = supply_order_videogames.supplyOrderID  
WHERE supply_orders.status = 'Completed' OR supply_orders.status = 'Shipped' OR supply_orders.status = 'Delayed'
ORDER BY processingDays;
/*This is a view that takes the shipped orders from the supply orders list and 
calculates in days how long each one took for order processing with the product names and company names. 
It sorts it from the lowest number of days to highest. It's good for the company 
to see how effective suppliers are in terms of fufiling orders for them. It can help 
identify if there are any issues with specific suppliers at hand. This is greatly important 
to the business as having stock as soon as possible is a must for the growth of the company. 
If they track far too many lengthy delays in the supply chain ordering process they 
can bring this up with the supplier having issues.*/
